(*
    PE Tool's strings and messages

    Copyright (c) 2012-2015 Vladislav Javadov (aka Freeman)

    Conditional defines:
      * Menuet -- MENUET01 and MENUET02 format help
      * Kolibri -- KolibriOS light PE format help
*)

unit PetConsts;

interface

{ Do not localize }

const
              // short Unicode strings
  sInto       = #4'into';
  sBackup     = #6'backup';
  sStub       = #4'stub';
  sExtract    = #7'extract';
  sDump       = #4'dump';

  s3GB        = #3'3GB';
  sAuto       = #4'auto';
  sCleanVer   = #8'cleanver';
  sDeep       = #4'deep';
  sDropRes    = #7'dropres';
  sDropSect   = #8'dropsect';
  sKolibri    = #7'kolibri';
  sKeep       = #4'keep';
  sLocale     = #6'locale';
  sMainIcon   = #8'mainicon';
  sMenuet     = #6'menuet';
  sMiniRes    = #7'minires';
  sNoLogo     = #6'nologo';
  sPause      = #5'pause';
  sRebase     = #6'rebase';
  sOSVer      = #5'osver';
  sSafe       = #4'safe';
  sStrip      = #5'strip';
  sTrunc      = #5'trunc';

  sLogo =
          #9'  /\_/\'#10 +
    '     ____/ o o \    %s %hs #ПокажиКота'#10 +
    '   /~____ ==t==/'#10 +
    '  (_______)_m_m)    %s'#10 +
    #10 +
    '      PET :-)';

{ Localize }

const
  sUsage =
    'Usage:'#9'%s <source> [commands [options]]';
  sHelp =
    'Commands'#10 +
            #9'-backup <bak>'#9#9'Backup <source> file to <bak> file'#10#10 +
          //  #9'-dump <dump>'#9'Dump <source> info to <dump> file'#10 +
            #9'-extract <stub>'#9#9'Extract <source> stub to <stub> file'#10 +
            #9'-into [dest]'#9#9'Save result to [dest] file'#10#10 +
    'Option for -extract and -into commands'#10 +
            #9'-strip'#9#9#9'Strip headers, relocations and empty sections'#10 +
            #9#9#9#9'when possible'#10#10 +
    'Options for -into command'#10 +
            #9'-3GB'#9#9#9'Set large address aware application flag'#10 +
//            #9'-cleanver'#9#9'Clean version info resource generated by Delphi'#10 +
            #9'-auto'#9#9#9'Using '#$E2#$80#$9C'-keep -strip -trunc -stub'#$E2#$80#$9D' mode, replace'#10 +
                   #9#9#9#9'original file when stripped size is equal or'#10 +
                   #9#9#9#9'greater than volume cluster'#10 +
            #9'-deep'#9#9#9'Strip orphaned sections too (unsafe!)'#10 +
//            #9'-dropres <r1,r2,...>'#9'Drop resources <r1>, <r2>, etc.'#10 +
            #9'-dropsect <s1,s2,...>'#9'Drop sections <s1>, <s2>, etc.'#10 +
            #9'-keep'#9#9#9'Keep original timestamp and attributes'#10 +
          {$IFDEF Kolibri}
            #9'-kolibri'#9#9'Save to KolibriOS light PE format'#10 +
          {$ENDIF}
//            #9'-locale <a1,a2,...>'#9'Set resource locales to <a1>, <a2>, etc.'#10 +
//            #9#9#9#9'Each <a> has form of <#=#> or <#>'#10 +
//            #9'-mainicon'#9#9'Strip the name of MAINICON resource (not for'#10 +
//            #9#9#9#9'VCL applications!)'#10 +
          {$IFDEF Menuet}
            #9'-menuet <#>'#9#9'Save to MENUET01 or MENUET02 format'#10 +
          {$ENDIF}
//            #9'-rebase <#>'#9#9'Change image base to <#> (hexadecimal value)'#10 +
            #9'-osver <#[.#]>'#9#9'Set required OS version to <#> or <#.#>'#10 +
            #9'-safe'#9#9#9'Stop stripping when overlay data or certificate'#10 +
                   #9#9#9#9'found'#10 +
            #9'-stub [stub]'#9#9'Replace stub with one from [stub] file'#10 +
            #9'-trunc'#9#9#9'Don''t align last section, truncate file'#10 +
                    #9#9#9#9'immediately after data end'#10#10 +
    'Miscellaneous options'#10 +
            #9'-nologo'#9#9#9'Don''t display PET logo'#10 +
            #9'-pause'#9#9#9'Wait for ENTER key to exit';

  sMissingParam = 'Missing %s';
  sDuplicateParam = 'Duplicate %hs: %s';
  sFileName = '%ws file name'; // CoreChar
  sSource = 'source';
  sOSVersion = 'OS version number';
  sSectionNames = 'section names';
  sResourceNames = 'resource names';
  sLocaleMap = 'locale map';
  sImageBase = 'image base value';

  sCannotRebaseImage = 'Cannot rebase image: %s';

  FileNameWidth = 48;
  FileNameOffset = 12;

  sProcessing     = '%-16hs %-32@s %8u bytes';

  sLoadingSource    = 'Loading source';
  sImageData        = 'Image data';
  sExtractingStub   = 'Extracting stub';
  sFixingStub       = 'Fixing stub';
  sInsertingStub    = 'Inserting stub';
  sSavingInto       = 'Saving into';
  sDroppingSection  = 'Dropping section';
  sDroppingResource = 'Dropping resource';
  sStripping        = 'Stripping';
  sTotal            = 'Total';

  sBackuping      = 'Backuping'#9' %s';

implementation

uses
  CoreConsts;

initialization
  LocalizationCP := 1251; // #ПокажиКота

end.

