(*
    Pythia -- Delphi to FASM preprocessor for Kolibri OS

    String messages

    Copyright © 2013 Vladislav Javadov (Freeman)
*)

unit PythiaConsts;

interface

{ Do not localize }

const
  sInto  = 'into';
  sDef   = 'def';
  sMap   = 'map';
  sSrc   = 'src';
  sPause = 'pause';

  sSlashSlash: string[2] = '//';
  sFunction: string[8] = 'function';
  sProcedure: string[9] = 'procedure';
  sConstructor: string[11] = 'constructor';
  sDestructor: string[10] = 'destructor';
  sEnd: string[3] = 'end';
  sImplementation: string[14] = 'implementation';
  sPtr: string[3] = 'ptr';
  sNear: string[4] = 'near';
  sLine: string[4] = 'Line';

{ Localize }

const
  sVersion    = '0.1';
  sTitle      = 'Pythia';
  sCopyright  = '%s %s  Copyright © 2013 Vladislav Javadov';
  sUsage      = 'Usage:'#9'%ws int-file -into dest-file [-def def-file] [-map map-file]'#10 +
                        #9'[-src source-file] [-pause]';

  sWarning = 'Warning: %s';
  sNoSourceLine = 'Line %d not found, source code contains only %d lines';
//  sNoFunctionNames = 'No function names found in the map file';
//  sEmptySourceCode = 'Source code file is empty';
  sNoImplementation = 'Implementation section not found';
  sIdentExpected = 'Identifier expected';
  sUnclosedComment = 'Unclosed comment';

  sDoNotEdit = '; Generated by %s, please DO NOT EDIT!';
  sSourceCodeLine = '; Line %d:  %s';
  sNotFound = 'not found';

  sLineCount = '%d lines(s)';
  sFuncCount = '%d function(s)';
  sNothingToSave = 'Nothing to save';

  sPressEnterToExit = 'Press ENTER to exit';

implementation

end.

