(*
    Pythia -- Delphi to FASM preprocessor for Kolibri OS

    String messages

    Copyright (c) 2013 Vladislav Javadov (Freeman)
*)

unit PythiaConsts;

interface

{ Do not localize }

const
  sInto  = 'into';
  sMap   = 'map';
  sSrc   = 'src';
  sPause = 'pause';


{ Localize }

const
  sVersion    = '0.1';
  sTitle      = 'Pythia';
  sCopyright  = '%s %s  Copyright (c) 2013 Vladislav Javadov';
  sUsage      = 'Usage:'#9'%ws int-file -into dest-file [-map map-file] [-src source-file]'#10 +
                        #9'[-pause]';

  sWarning = 'Warning: %s';
  sNoSourceLine = 'Line %d not found, source code contains only %d lines';
//  sNoFunctionNames = 'No function names found in the map file';
//  sEmptySourceCode = 'Source code file is empty';
  sNoImplementation = 'Implementation section not found';
  sIdentExpected = 'Identifier expected';
  sUnclosedComment = 'Unclosed comment';

  sDoNotEdit = '; Generated by %s, please DO NOT EDIT!';
  sSourceCodeLine = '; Line %d:  %s';
  sNotFound = 'not found';

  sLineCount = '%d lines(s)';
  sFuncCount = '%d function(s)';
  sNothingToSave = 'Nothing to save';

  sPressEnterToExit = 'Press ENTER to exit';

implementation

end.

