;
;   Kolibri OS Unicode Library (UnicodeLib)
;
;   Code page names -- English and Russian
;   Used CP866 character set as needed for Kolibri
;
;   Copyright (c) 2012 The Unified Environment Laboratory
;

sRu437  db  'США (DOS)', 0
sRu737  db  'Греческая (DOS)', 0
sRu775  db  'Балтийская (DOS)', 0
sRu850  db  'Западноевропейская (DOS)', 0
sRu852  db  'Центральноевропейская (DOS)', 0
sRu855  db  'Кириллица (DOS)', 0
sRu857  db  'Турецкая (DOS)', 0
;sRu858  db  'Западноевропейская + Евро (DOS)', 0
sRu860  db  'Португальская (DOS)', 0
sRu861  db  'Исландская (DOS)', 0
;sRu862  db  'Hebrew (DOS)', 0
sRu863  db  'Франко-канадская (DOS)', 0
sRu865  db  'Скандинавская (DOS)', 0
sRu866  db  'Русская (DOS)', 0

sRu1250  db  'Центральноевропейская (Windows)', 0
sRu1251  db  'Кириллица (Windows)', 0
sRu1252  db  'Западноевропейская (Windows)', 0
sRu1253  db  'Греческая (Windows)', 0
sRu1254  db  'Турецкая (Windows)', 0
;sRu1255  db  'Иврит (Windows)', 0
;sRu1256  db  'Арабская (Windows)', 0
sRu1257  db  'Балтийская (Windows)', 0

sRu20866  db  'Русская КОИ-8', 0
sRu21866  db  'Украинская КОИ-8', 0

sRu28591  db  'Западноевропейская (ISO 8859-1)', 0
sRu28592  db  'Центральноевропейская (ISO 8859-2)', 0
sRu28593  db  'Латинская 3 (ISO 8859-3)', 0
sRu28594  db  'Балтийская (ISO 8859-4)', 0
sRu28595  db  'Кириллица (ISO 8859-5)', 0
sRu28597  db  'Греческая (ISO 8859-7)', 0
sRu28599  db  'Латинская 5 (ISO 8859-9)', 0
sRu28605  db  'Латинская 9 (ISO 8859-15)', 0

sEn437  db  'United States (DOS)', 0
sEn737  db  'Greek (DOS)', 0
sEn775  db  'Baltic (DOS)', 0
sEn850  db  'Western European (DOS)', 0
sEn852  db  'Central European (DOS)', 0
sEn855  db  'Cyrillic (DOS)', 0
sEn857  db  'Turkish (DOS)', 0
;sEn858  db  'Western European + Euro (DOS)', 0
sEn860  db  'Portuguese (DOS)', 0
sEn861  db  'Icelandic (DOS)', 0
;sEn862  db  'Hebrew (DOS)', 0
sEn863  db  'Canadian French (DOS)', 0
sEn865  db  'Nordic (DOS)', 0
sEn866  db  'Russian (DOS)', 0

sEn1250  db  'Central European (Windows)', 0
sEn1251  db  'Cyrillic (Windows)', 0
sEn1252  db  'Western European (Windows)', 0
sEn1253  db  'Greek (Windows)', 0
sEn1254  db  'Turkish (Windows)', 0
;sEn1255  db  'Hebrew (Windows)', 0
;sEn1256  db  'Arabic (Windows)', 0
sEn1257  db  'Baltic (Windows)', 0

sEn20866  db  'KOI8-Russian', 0
sEn21866  db  'KOI8-Ukrainian', 0

sEn28591  db  'Western European (ISO 8859-1)', 0
sEn28592  db  'Central European (ISO 8859-2)', 0
sEn28593  db  'Latin 3 (ISO 8859-3)', 0
sEn28594  db  'Baltic (ISO 8859-4)', 0
sEn28595  db  'Cyrillic (ISO 8859-5)', 0
sEn28597  db  'Greek (ISO 8859-7)', 0
sEn28599  db  'Latin 5 (ISO 8859-9)', 0
sEn28605  db  'Latin 9 (ISO 8859-15)', 0
