;
;   Kolibri OS Unicode Library (UnicodeLib)
;
;   Raw code page translation tables
;
;   Copyright (c) 2012 The Unified Environment Laboratory
;

CodePageNamesRu:
  dd sRu437
  dd sRu737
  dd sRu775
  dd sRu850
  dd sRu852
  dd sRu855
  dd sRu857
  dd sRu860
  dd sRu861
  dd sRu863
  dd sRu865
  dd sRu866

  dd sRu1250
  dd sRu1251
  dd sRu1252
  dd sRu1253
  dd sRu1254
  dd sRu1257

  dd sRu20866
  dd sRu21866

  dd sRu28591
  dd sRu28592
  dd sRu28593
  dd sRu28594
  dd sRu28595
  dd sRu28597
  dd sRu28599
  dd sRu28605

CodePageNamesEn:
  dd sEn437
  dd sEn737
  dd sEn775
  dd sEn850
  dd sEn852
  dd sEn855
  dd sEn857
  dd sEn860
  dd sEn861
  dd sEn863
  dd sEn865
  dd sEn866

  dd sEn1250
  dd sEn1251
  dd sEn1252
  dd sEn1253
  dd sEn1254
  dd sEn1257

  dd sEn20866
  dd sEn21866

  dd sEn28591
  dd sEn28592
  dd sEn28593
  dd sEn28594
  dd sEn28595
  dd sEn28597
  dd sEn28599
  dd sEn28605

